/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Artist } from './artist.type';
import { Copyright } from './copyright.type';
import { ExternalIDS } from './externalIDS.type';
import { Tracks } from './tracks.type';
import { Image } from './image.type';
import { ExternalUrls } from './externalUrls.type';


export interface AlbumDetail { 
    album_type: string;
    artists: Array<Artist>;
    available_markets: Array<string>;
    copyrights: Array<Copyright>;
    external_ids: ExternalIDS;
    external_urls: ExternalUrls;
    genres: Array<any>;
    href: string;
    id: string;
    images: Array<Image>;
    name: string;
    popularity: number;
    release_date: number;
    release_date_precision: string;
    tracks: Tracks;
    type: string;
    uri: string;
}

