/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AlbumType = 'ALBUM' | 'SINGLE' | 'COMPILATION';

export const AlbumType = {
    ALBUM: 'ALBUM' as AlbumType,
    SINGLE: 'SINGLE' as AlbumType,
    COMPILATION: 'COMPILATION' as AlbumType
};

