/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlbumTypeEnum } from './albumTypeEnum.type';
import { Artist } from './artist.type';
import { ReleaseDatePrecision } from './releaseDatePrecision.type';
import { AlbumType } from './albumType.type';
import { Image } from './image.type';
import { ExternalUrls } from './externalUrls.type';


export interface Album { 
    album_type: AlbumType;
    artists: Array<Artist>;
    available_markets: Array<string>;
    external_urls: ExternalUrls;
    href: string;
    id: string;
    images: Array<Image>;
    name: string;
    release_date: string;
    release_date_precision: ReleaseDatePrecision;
    total_tracks: number;
    type: AlbumTypeEnum;
    uri: string;
}

