/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtistType } from './artistType.type';
import { Followers } from './followers.type';
import { Image } from './image.type';
import { ExternalUrls } from './externalUrls.type';


export interface ArtistDetail { 
    external_urls: ExternalUrls;
    followers: Followers;
    genres: Array<string>;
    href: string;
    id: string;
    images: Array<Image>;
    name: string;
    popularity: number;
    type: ArtistType;
    uri: string;
}

