/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Artist } from './artist.type';
import { ExternalIDS } from './externalIDS.type';
import { ItemType } from './itemType.type';
import { Album } from './album.type';
import { ExternalUrls } from './externalUrls.type';


export interface Tracks { 
    album: Album;
    artists: Array<Artist>;
    available_markets: Array<string>;
    disc_number: number;
    duration_ms: number;
    explicit: boolean;
    external_ids: ExternalIDS;
    external_urls: ExternalUrls;
    href: string;
    id: string;
    is_local: boolean;
    name: string;
    popularity: number;
    preview_url: string;
    track_number: number;
    type: ItemType;
    uri: string;
}

