/**
 * Spotify API
 * Spotify API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArtistDetail } from './artistDetail.type';


export interface UserTopArtists { 
    items: Array<ArtistDetail>;
    total: number;
    limit: number;
    offset: number;
    href: string;
    previous: string;
    next: string;
}

